### ISSUE TITLE
Can't see the option after importing plugin and restarting

### ISSUE THREAD

**Issue by florentdestremau** [baptistemesta/power-mode-intellij-plugin#4]
and no results from the search bar in my settings :sob: 

Using PhpStorm 10, may be related to this

**Comment by axaluss** [comment]
This is a deprecation issue of the plugin.xml.
fixed here: 
https://github.com/axaluss/power-mode-intellij-plugin
 https://plugins.jetbrains.com/plugin/8125?pr=
